// LA LOGICA QUE DEBERIAS IMPLEMENTAR ES QUE ESTO SEA UN MODAL COMO PROPUSISTE
// ENTONCES SI SE MUESTRA O NO ES UN BOOLEANO QUE DEBERIA RECIBIR POR PARAMETRO POR EJEMPLO ISOPEN
// ESE ISOPEN SE VA A CAMBIAR DESDE EL PADRE QUE VA A SER EL COMPONENTE DE PRODUCTS PAGE

export const NewProduct = () => {
  return <div>NewProduct</div>;
};
